### ISSUE TITLE
Image orientation

### ISSUE THREAD

**Issue by gomako** [gordalina/faced#10]
I tried this out on an image and it didn't seem to work. When I looked at the `.features` output the image was in a landscape orientation (rotated -90degrees). If I copy and paste and save the image out again it works as expected.

I would love to be able to fix this myself but I don't really know where to start! I guess you could check for orientation data somehow?

**Comment by gordalina** [comment]
You mean that the original image is in portrait mode, but when ran through the example it rotated to landscape?
The example does not rotate the image.

**Comment by gomako** [comment]
That's correct. When I look at the EXIF data for the image in question, Orientation is set to 6 which I think means that the image is to be rotated 90 CCW. I ran the image through [EXIFTrans](https://linux.die.net/man/1/exiftran) which looks at the orientation tag, rotates the image then strips the tag out and it worked great.
If the orientation tag is set to 1 then everything works as expected.

**Comment by gordalina** [comment]
I'd recommend rotating the image by yourself first, before running it through the example script. This is outside of scope for this project.

**Comment by gomako** [comment]
![portrait_6](https://user-images.githubusercontent.com/1306421/31514342-3ea140e0-af89-11e7-9749-9f7afde93c76.jpg)

This is an example image with the EXIF rotation tag. It's from [this repo](https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_6.jpg)

**Comment by gomako** [comment]
Ok, no problem. Thanks.
