### ISSUE TITLE
Error on install.

### ISSUE THREAD

**Issue by JohnPett** [gordalina/faced#5]
There seems to be a module conflict when installing. My console says:

`npm ERR! Failed at the opencv@0.3.1 preinstall script 'node-gyp clean rebuild'.
npm ERR! This is most likely a problem with the opencv package`

Then in the npm.log file, it appears to have a conflict with some other globally installed modules:

`310 info preuninstall faced@1.1.3
311 info uninstall faced@1.1.3
312 verbose unbuild rmStuff faced@1.1.3 from /usr/local/lib/node_modules
313 info postuninstall faced@1.1.3
314 silly gentlyRm /usr/local/lib/node_modules/faced is being purged from base /usr/local
315 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/faced
316 silly vacuum-fs purging /usr/local/lib/node_modules/faced
317 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules`

Is this something you have experienced?

**Comment by gordalina** [comment]
No I haven't, which node version are you using?

**Comment by JohnPett** [comment]
Hi Samuel,

Thanks for getting back. I'm using the latest version:

v0.12.4

JP

**Comment by gordalina** [comment]
I'll update to opencv 3.0.0, that might do the trick.

**Comment by JohnPett** [comment]
Thanks! I would much rather use your simple API than they others that are
available.

**Comment by lschans** [comment]
Is there a solution? I faced the same problem.. 

I am using opencv 3 compiled with brew on el Capitan. I am using node v4.1.0.

When installing your package I get the following output:

npm ERR! Failed at the opencv@0.3.1 preinstall script 'node-gyp clean rebuild'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean rebuild

Looking at the comments in this issue it seems that there is a solution, but just not mentioned here.

**Comment by JohnPett** [comment]
@lschans I used this instead as I couldn't get this one working: https://github.com/peterbraden/node-opencv

**Comment by lschans** [comment]
Okay lemme try that one,

thanks

**Comment by gordalina** [comment]
@JohnPett which version did you use? `3.2.0`?
I can update `package.json` to work without any local modifications.

**Comment by JohnPett** [comment]
Ah, it is using 2.4.12, thank you @gordalina !

**Comment by qwemaze** [comment]
Same problem, can someone define a solution?

**Comment by qwemaze** [comment]
Well I uninstalled my OpenCV v3.1.0, did apt-get install libopencv-dev which is 2.3.1 and updated dependency to opencv package to v5.0.0.
And it's worked, but in a very weird way.

**Comment by MalvinMiao** [comment]
@qwemaze I have the same issue, the library works with opencv 5.0.0, but detect the face in a wrong way, have you resolved it? Could you please give me some hints here? Thank you in advance.

**Comment by qwemaze** [comment]
@MalvinMiao nope :(
Used [this](https://www.npmjs.com/package/face-detect) instead.

**Comment by MalvinMiao** [comment]
@qwemaze Thank you so much :)

**Comment by aralroca** [comment]
Same problem 😣

**Comment by gordalina** [comment]
Fixed these issues.
You *must* use opencv `~2.4`.
I've updated the README with installation procedures.
Thanks everyone

**Comment by gordalina** [comment]
Released `1.2.0`
